import styles from "styles/Home.module.css";

import type { GetStaticProps, GetStaticPropsContext, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Card from "components/Card";
import List from "components/List";

const Home: NextPage = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <List withForm />

        <div className={styles.grid}>
          <Card
            title="Documentation &rarr;"
            body="Find in-depth information about Next.js features and API."
          />
          <Card
            title="Learn &rarr;"
            body="Learn about Next.js in an interactive course with quizzes!"
          />
          <Card
            title="Examples &rarr;"
            body="Discover and deploy boilerplate example Next.js projects."
          />
          <Card
            title="Deploy &rarr;"
            body="Instantly deploy your Next.js site to a public URL with Vercel."
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (
  ctx: GetStaticPropsContext
) => {
  return {
    props: {
      test: true,
    },
  };
};

export default Home;
